# Generated by Django 2.2.6 on 2021-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[('1', 'механика'), ('2', 'автомат'), ('3', 'робот')])),
                ('color', models.CharField(max_length=150)),
            ],
        ),
    ]
