# Generated by Django 2.2.6 on 2021-04-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')]),
        ),
    ]
